spring.application.name=ms-inventory
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

spring.neo4j.uri=bolt://${DB_HOST}:7687
spring.neo4j.authentication.username=${DB_USER}
spring.neo4j.authentication.password=${DB_PASSWORD}
spring.data.neo4j.database=${DB_NAME:neo4j}
